### ISSUE TITLE
Interactive slider with zero particle data

### ISSUE THREAD

**Issue by x113f** [openPMD/openPMD-viewer#226] opened 2018-10-25 11:56 UTC
If I open particle data with zero value, I get the following error:

```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/opmd_viewer/openpmd_timeseries/interactive.py in step_fw(b)
    267             else:
    268                 self.current_iteration = self.iterations[self._current_i]
--> 269             slider.value = self.current_iteration
    270 
    271         def step_bw(b):

/opt/pkg/devel/python/3.6.2/lib/python3.6/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    583             raise TraitError('The "%s" trait is read-only.' % self.name)
    584         else:
--> 585             self.set(obj, value)
    586 
    587     def _validate(self, obj, value):

/opt/pkg/devel/python/3.6.2/lib/python3.6/site-packages/traitlets/traitlets.py in set(self, obj, value)
    572             # we explicitly compare silent to True just in case the equality
    573             # comparison above returns something other than True/False
--> 574             obj._notify_trait(self.name, old_value, new_value)
    575 
    576     def __set__(self, obj, value):

/opt/pkg/devel/python/3.6.2/lib/python3.6/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
   1137             new=new_value,
   1138             owner=self,
-> 1139             type='change',
   1140         ))
   1141 

/opt/pkg/devel/python/3.6.2/lib/python3.6/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    598                 # Send new state to front-end
    599                 self.send_state(key=name)
--> 600         super(Widget, self).notify_change(change)
    601 
    602     def __repr__(self):

/opt/pkg/devel/python/3.6.2/lib/python3.6/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1174                 c = getattr(self, c.name)
   1175 
-> 1176             c(change)
   1177 
   1178     def _add_notifiers(self, handler, name, type):

~/.local/lib/python3.6/site-packages/opmd_viewer/openpmd_timeseries/interactive.py in change_iteration(change)
    259             self.current_iteration = self.iterations[ self._current_i ]
    260             refresh_field()
--> 261             refresh_ptcl()
    262 
    263         def step_fw(b):

~/.local/lib/python3.6/site-packages/opmd_viewer/openpmd_timeseries/interactive.py in refresh_ptcl(change, force)
    170                         nbins=ptcl_bins_button.value,
    171                         plot_range=plot_range,
--> 172                         use_field_mesh=ptcl_use_field_button.value, **kw_ptcl )
    173                 else:
    174                     # 2D histogram

~/.local/lib/python3.6/site-packages/opmd_viewer/openpmd_timeseries/main.py in get_particle(self, var_list, species, t, iteration, select, output, plot, nbins, plot_range, use_field_mesh, histogram_deposition, **kw)
    332                 self.plotter.hist1d(data_list[0], w, var_list[0], species,
    333                         self._current_i, hist_bins[0], hist_range,
--> 334                         deposition=histogram_deposition, **kw)
    335             # - In the case of two quantities
    336             elif len(data_list) == 2:

~/.local/lib/python3.6/site-packages/opmd_viewer/openpmd_timeseries/plotter.py in hist1d(self, q1, w, quantity1, species, current_i, nbins, hist_range, cmap, vmin, vmax, deposition, **kw)
    109         elif deposition == 'cic':
    110             binned_data = histogram_cic_1d(
--> 111                 q1, w, nbins, hist_range[0][0], hist_range[0][1])
    112         else:
    113             raise ValueError('Unknown deposition method: %s' % deposition)

opmd_viewer/openpmd_timeseries/cython_function.pyx in opmd_viewer.openpmd_timeseries.cython_function.histogram_cic_1d()

ZeroDivisionError: float division
```

**Comment by ax3l** [comment] 2018-10-25 12:15
@RemiLehe the particles that were visualized here are particle probes: https://picongpu.readthedocs.io/en/0.4.0/usage/workflows/probeParticles.html

Since the attribute checked here is part of the `ED-PIC` extension, we could use a reasonable fallback if only the base standard attributes are available.

**Comment by RemiLehe** [comment] 2018-10-25 21:22
Thanks for reporting this issue!
Would it be possible that you send the openPMD file that resulted in this error (via private email for instance)? Or create a minimal reproduced if the file is too big?
Also, which quantites were you trying to visualize here (e.g. `x`? `uy`? `Ex`?)

**Comment by ax3l** [comment] 2018-10-25 21:44
The default that is visualized is `probeB/x` which is a vector component of the probe species that records the B field. We can check the file and submit it, should not be too large. I just saw that I misread the error message and it's indeed something thrown during the value binning in the histogram method.

**Comment by ax3l** [comment] 2018-10-25 21:45
@x113f can you please compress your `simOutput/h5/simData_0.h5` file with this script:
https://github.com/ax3l/cluster-scripts/blob/master/bash-h5compress.sh
?

Afterwards, if it is not too large, GitHub should allow you to append it to a comment if you append a `.txt` to the file ending (or zip it).

**Comment by x113f** [comment] 2018-10-26 09:01
This is the one of the data files, where it raises the error:
[https://owncloud.physik.uni-muenchen.de/index.php/s/qHHq8TNtWySoJqW](https://owncloud.physik.uni-muenchen.de/index.php/s/qHHq8TNtWySoJqW)

This is the minimum example. I get the error, when I press  refresh for the particle quantities.
```python
from opmd_viewer import OpenPMDTimeSeries
ts = OpenPMDTimeSeries('path/to/file/')
ts.slider()
```

**Comment by ax3l** [comment] 2021-03-25 03:31
I think this is fixed now :)

**Closed by ax3l** 2021-03-25 03:31 UTC
Labels: bug, interactive
